[pytest]
markers = 
    sanity
    regression


# Run command for parameterize markers:-
# pytest -v -s -m "sanity" --html=./Reports/report.html testCases/ --browser chrome
# pytest -v -s -m "regression" --html=./Reports/report.html testCases/ --browser chrome
# pytest -v -s -m "sanity and regression" --html=./Reports/report.html testCases/ --browser chrome
# pytest -v -s -m "sanity or regression" --html=./Reports/report.html testCases/ --browser chrome


################### Pytest HTML Report #############################
# pytest -v -s -n=2 --html=Reports\report.html testCases\test_login.py --browser chrome

# To run test parallel :-  
# pytest -v -s -n=2 testCases\test_login.py --browser chrome

# To run for different browsers :-
# pytest -v -s testCases\test_login.py --browser chrome
# pytest -v -s testCases\test_login.py --browser edge